name: StarNotify
version: 1.0-SNAPSHOT
main: dev.ha1zen.StarNotify
api-version: 1.21
folia-supported: true
description: Добавляет уведомления при входе/выходе игроков
authors:
  - ha1zenstar
commands:
  mynotify:
    description: Устанавливает собственное сообщение входа/выхода
    usage: /<command> <Уведомление>
    permission: starnotify.mynotify
    permission-message: §cУ вас нет разрешения на использование этой команды!
  notify:
    description: Вкл / выкл уведомления входа / выхода
    usage: /<command> <true|false>
    permission: starnotify.notifystate